### ISSUE TITLE
Mismatched Jackson lib in demo

### ISSUE THREAD

**Issue by SteveHarney** [virgo47/javasimon#16]
In the 4.1.2 snapshot It appears that the version of the jackson library (2.0.4) provided under the demoapp is incompatible with the recently updated spring version ( 4.1.6.RELEASE).    This results in the stack trace below when you try to create new item in the demo.   spring 4.1.6 was compiled against jackson 2.5.4 and that at least resolves this issue. 

java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.getFactory()Lcom/fasterxml/jackson/core/JsonFactory;
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:217)
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:208)

<snip>
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:643)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.javasimon.javaee.SimonServletFilter.doFilterWithMonitoring(SimonServletFilter.java:245)

**Comment by virgo47** [comment]
You're right, I didn't check item creation problems. I upgraded the jackson lib to 2.5.4 and it works fine now.
